ALTER TABLE users ADD COLUMN IF NOT EXISTS badge_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS rank VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS station VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(200);
